const preElt = document.querySelector("#pre"),
    themesElt = document.querySelector("#themes"),
    timeElt = document.querySelector("#time"),
    scoreElt = document.querySelector("#score"),
    postElt = document.querySelector("#post"),
    finalElt = document.querySelector("#final"),
    againElt = document.querySelector("#again"),
    main = document.querySelector('.container'),
    timer = document.querySelector(".time"),
    state = document.querySelector("#state"),
    overlay = document.querySelector('.overlay'),
    modal = document.getElementById("popup1");

let idOfBtn = '';
let hasFlippedCard = false;
let lockBoard = false;
let firstCard, secondCard;
let firstBackCard, secondBackCard;
let matchedCard = 0;
let score = 0,
    moves = 0,
    time = 0,
    second = 0,
    minute = 0,
    interval,
    choosenTheme;

var games = {
    animals: [
        'images/animal/cat.svg',
        'images/animal/cow.svg',
        'images/animal/dog.svg',
        'images/animal/elephant.svg',
        'images/animal/lion.svg',
        'images/animal/owl.svg',
        'images/animal/cat.svg',
        'images/animal/cow.svg',
        'images/animal/dog.svg',
        'images/animal/elephant.svg',
        'images/animal/lion.svg',
        'images/animal/owl.svg'
    ],
    superhero: [
        'images/superhero/1_superhero.svg',
        'images/superhero/2_superhero.svg',
        'images/superhero/3_superhero.svg',
        'images/superhero/4_superhero.svg',
        'images/superhero/5_superhero.svg',
        'images/superhero/6_superhero.svg',
        'images/superhero/7_superhero.svg',
        'images/superhero/8_superhero.svg',
        'images/superhero/1_superhero.svg',
        'images/superhero/2_superhero.svg',
        'images/superhero/3_superhero.svg',
        'images/superhero/4_superhero.svg',
        'images/superhero/5_superhero.svg',
        'images/superhero/6_superhero.svg',
        'images/superhero/7_superhero.svg',
        'images/superhero/8_superhero.svg',
    ],
    wildwest: [
        'images/wildwest/cactus.svg',
        'images/wildwest/cowboy.svg',
        'images/wildwest/gun.svg',
        'images/wildwest/indian.svg',
        'images/wildwest/money.svg',
        'images/wildwest/saloon.svg',
        'images/wildwest/wagon.svg',
        'images/wildwest/whiskey.svg',
        'images/wildwest/cactus.svg',
        'images/wildwest/cowboy.svg',
        'images/wildwest/gun.svg',
        'images/wildwest/indian.svg',
        'images/wildwest/money.svg',
        'images/wildwest/saloon.svg',
        'images/wildwest/wagon.svg',
        'images/wildwest/whiskey.svg'
    ],
    animalsNames: [
        "cat",
        "cow",
        "dog",
        "elephant",
        "lion",
        "owl",
        "cat",
        "cow",
        "dog",
        "elephant",
        "lion",
        "owl"
    ],
    superheroNames: [
        "1_superhero",
        "2_superhero",
        "3_superhero",
        "4_superhero",
        "5_superhero",
        "6_superhero",
        "7_superhero",
        "8_superhero",
        "1_superhero",
        "2_superhero",
        "3_superhero",
        "4_superhero",
        "5_superhero",
        "6_superhero",
        "7_superhero",
        "8_superhero",
    ],
    wildWestNames: [
        "cactus",
        "cowboy",
        "gun",
        "indian",
        "money",
        "saloon",
        "wagon",
        "whiskey",
        "cactus",
        "cowboy",
        "gun",
        "indian",
        "money",
        "saloon",
        "wagon",
        "whiskey",
    ],
    themes: [
        "Animals",
        "Superhero",
        "WildWest"
    ]
}